baseURL = "https://examplewww.benjaminpaulus.com/"
languageCode = "en-us"
title = "Ben Paulus"
theme = "hugo-minimal-theme"
# disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "Ben Paulus"
    description = "Content Leadership, Strategy, & Design"
    githubUsername = "virtual-ben"
    accent = "#554C4A"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 3

# [[menu.main]]
#     url = "/post/"
#     name = "Posts"
#     weight = 4

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:benjamin.a.paulus@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/virtual-ben/"
    name = "github"
    weight = 2

# [[menu.icon]]
#     url = "https://twitter.com/username/"
#     name = "twitter"
#     weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/ben-paulus/"
    name = "linkedin"
    weight = 4

# [[menu.icon]]
#     url = "https://www.stackoverflow.com/username/"
#     name = "stack-overflow"
#     weight = 5
